spring:
    application:
        name: register-center
    security:
      user:
        name: huwl
        password: huwl

eureka:
  instance:
    prefer-ip-address: false #true实例以 IP 的形式注册 false：实例以机器 HOSTNAME 形式注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #表示实例在注册中心注册的唯一ID
    lease-expiration-duration-in-seconds: 30 #表示 Eureka Server 在接收到上一个心跳之后等待下一个心跳的秒数（默认 90 秒），若不能在指定时间内收到心跳，则移除此实例，并禁止此实例的流量,需要设置为至少高于 lease-renewal-interval-in-seconds 的值，不然会被误移除了
    lease-renewal-interval-in-seconds: 5 #表示 Eureka Client 向 Eureka Server 发送心跳的频率（默认 30 秒），如果在 lease-expiration-duration-in-seconds 指定的时间内未收到心跳，则移除该实例
  server:
    enable-self-preservation: true #开启自我保护机制，默认开启
    renewal-percent-threshold: 0.85 #开启自我保护的系数，默认：0.85
    eviction-interval-timer-in-ms: 5000 #表示 Eureka Server 清理无效节点的频率，默认 60000 毫秒
  client:
    register-with-eureka: true #表示此实例是否注册到 Eureka Server 以供其他实例发现。在某些情况下，如果你不想自己的实例被发现，而只想发现其他实例，配置为 false 即可
    fetch-registry: true #表示客户端是否从 Eureka Server 获取实例注册信息
    serviceUrl:
      defaultZone: http://huwl:huwl@eureka1:8761/eureka/, http://huwl:huwl@eureka2:8762/eureka/ #表示客户端需要注册的 Eureka Server 的地址

logging.level.com.netflix:
  eureka: OFF
  discovery: OFF

---
spring:
  profiles: rc1

server:
  port: 8761

eureka.instance.hostname: eureka1

---
spring:
  profiles: rc2

server:
  port: 8762

eureka.instance.hostname: eureka2